# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Just4U
brief-intro: 不会算圈图的汽车电子工程师不是个好程序员
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.whatsroot.xyz/" # the base hostname & protocol for your site
future: true

permalink: /:year/:month/:day/:title/

# other links
facebook_username: 
github_username:  leeyeel
email: mumuli52@gmail.com
zhihu_username:
linkedIn_username: 
dribbble_username:
description_footer: 

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
livere_shortname: leo 
disqus_shortname: #leeyeel

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: 98486c072d947dfe59fdc38c1633941a 
# google 分析追踪id
google_analytics_id: UA-136580640-1
# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
#plugins: [jekyll-paginate]
#paginate: 6

plugins:
    - jekyll-sitemap
    - jekyll-paginate

paginate: 6
